//export const MAIN_HOST = "https://tagflowprobackend-production.up.railway.app";
export const MAIN_HOST = "http://localhost:5500";
export const API_URL = `${MAIN_HOST}/api`;
export const ITEMS_PER_PAGE = 5;
export const ADMIN_ROLE_ID = 1;
export const USERS_TABLE_TYPE = "Users";
export const ADMINS_TABLE_TYPE = "Admins";
export const USERS_AND_ADMINS_SEARCH_PLACEHOLDER =
  "Search with a username or an email";
export const TAGS_TABLE_TYPE = "Tags";
export const PROJECTS_TABLE_TYPE = "Projects";
export const PATIENT_TYPES_TABLE_TYPE = "PatientTypes";
export const TAGS_PLACEHOLDER = "Search with a tag name";
export const OPERATOR_ROLE_ID = 2;
export const VIEWER_ROLE_ID = 3;
export const UNPROCESSED_FILE_STATUS = "Unprocessed";
export const FILENAME_SEARCH_PLACEHOLDER = "Search with a file name";
export const PROJECTS_PLACEHOLDER = "Search with a project name";
export const PATIENT_TYPES_PLACEHOLDER = "Search with a patient type";
